name: VON DI CARLO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37187
title: 'VON DI CARLO '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a98ea671-a664-4565-8fba-8d9b720fb532.pdf
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f865166d-d036-49a8-87be-315b60d91f1f.jpg
  type: null
  appId: null
color:
  brandColors:
    - '#0F0100'
    - '#3C5B55'
    - '#FFFFFF'
    - '#FF1F16'
    - '#649484'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
