name: VON DI CARLO
favicon: null
layout_spectrum: 0.46641561249271035
typography_spectrum: 0.6155015958938748
title: 'VON DI CARLO '
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a98ea671-a664-4565-8fba-8d9b720fb532.pdf
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/f865166d-d036-49a8-87be-315b60d91f1f.jpg
  type: null
  appId: null
color:
  brandColors:
    - '#00585F'
    - '#009393'
    - '#FFFCC4'
    - '#F0EDBB'
    - '#FF3800'
  brandStrength: 0.4810774528887123
  lightness: 0.7504254402592778
  saturation: 0.06047556595876813
  rhythmicContrast: 0.49104194436222315
purpose: []
